version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: smart-home-postgres
    restart: always
    environment:
      POSTGRES_DB: smarthome
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  temperature-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    container_name: temperature-api
    ports:
      - "8081:8081"
    environment:
      ASPNETCORE_URLS: http://+:8081
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=smarthome;Username=postgres;Password=postgres
      Kafka__BootstrapServers: kafka:9092
    depends_on:
      - postgres
      - kafka
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    command:
      - bash
      - -c
      - |
        /usr/bin/kafka-storage format \
          --cluster-id zD9DxdF97qUkpTgpiTRR1w \
          --config /etc/kafka/kafka.properties \
          --ignore-formatted
    volumes:
      - ./kafka.properties:/etc/kafka/kafka.properties:ro
      - kafka_data:/var/lib/kafka/data
 
volumes:
  postgres_data:
  kafka_data:
