@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml


Person(customer, "Клиент", "Владелец дома с датчиками")
Person(technician, "Мастер", "Устанавливает и настраивает датчики через мобильное приложение")

Boundary(core, "Coziness (core domain)") {

Boundary(management, "Warmhouse management (subdomain)") {
    Boundary(warmcontext, "Heating management (bounded context)") {
        System(warmhouse, "WarmHouse (монолит)", "Управляет данными и логикой умного дома")
    }
    System_Ext(externalAPI, "Temperature API", "Внешняя система получения данных от датчиков (или edge-шлюза)")

    Rel(customer, warmhouse, "Управляет устройствами через", "веб или мобильное приложение")
    Rel(warmhouse, externalAPI, "Запрашивает температуру по sensorID или location")
}

Boundary(support, "Customer service (subdomain)") {
    System_Ext(mobileApp, "Приложение мастера (предположение)", "Используется для настройки и ввода новых датчиков")
    System_Ext(sensors, "Умные датчики", "Физические устройства в домах клиентов")

    Rel(technician, mobileApp, "Использует для настройки устройств")
    Rel(mobileApp, warmhouse, "Отправляет данные по", "REST API")
    Rel(sensors, externalAPI, "Отправляют данные или доступны через", "MQTT/REST/edge API")
}

}
@enduml
