@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(user, "Пользователь", "Управляет системой через приложения или ассистентов")

Boundary(coziness, "Coziness (core domain)") {

    System(system, "Умный дом", "Центральная система управления устройствами и взаимодействий")

    System_Ext(nativeDevices, "Нативные устройства", "Родные устройства")
    System_Ext(partnerDevices, "Устройства партнёров", "Сторонние устройства с поддержкой интеграции")
    System_Ext(voiceAssistant, "AI-ассистенты", "Голосовые помощники: Alexa, Google Assistant и т.п.")
    System_Ext(feedbackSystem, "СRM/CallCenter Software", "Принимает фидбек пользователей и создаёт тикеты в системе")
    System_Ext(cams, "Cams", "Камеры/прочие поточные устройства")

    Rel(user, system, "Управляет через интерфейсы, приложения")
    Rel(voiceAssistant, system, "Передаёт команды", "REST/MQTT")
    Rel(nativeDevices, system, "Интегрированы напрямую", "REST/MQTT")
    Rel(cams, system, "Интегрированы напрямую", "WebRTC")
    Rel(partnerDevices, system, "Работают через шлюзы", "REST/MQTT")
    Rel(user, feedbackSystem, "Оставляет фидбек, запрашивает помощь", "Web / Mobile")
    Rel(feedbackSystem, system, "Создаёт тикеты", "REST/MQTT")

}
@enduml
